-- Q6) Calculate the revenue generated by each flight, including payment status for all bookings made.

-- Step 1: we select the latest status for each flight
WITH latest_flight_status AS (
    SELECT 
        fls.flight_id,
        fls.status
    FROM flight_status fls
    INNER JOIN (
        -- Subquery to get the maximum last_updated value for each flight_id
        SELECT 
            flight_id, 
            MAX(last_updated) AS last_updated
        FROM flight_status
        GROUP BY flight_id
    ) latest ON fls.flight_id = latest.flight_id AND fls.last_updated = latest.last_updated
),

-- Step 2: we filter out those flights that have been canceled (we won't count them as revenues as they will have to be refunded)
non_canceled_flights AS (
    SELECT 
        flight_id,
        status
    FROM latest_flight_status
    WHERE status != 'CANCELED'
)

-- Step 3: we now compute the revenue with the flights that have not been canceled

SELECT
	b.flight_id AS flight_id,
	-- We sum the total revenue per flight
	SUM(bd.price) AS total_revenue, 
	-- We count the number of bookings depending on their payment status
	COUNT(CASE WHEN bd.payment_status = 'ACCEPTED' THEN 1 END) AS accepted_payments,
    COUNT(CASE WHEN bd.payment_status = 'REJECTED' THEN 1 END) AS rejected_payments
FROM booking_details bd
INNER JOIN booking b ON bd.booking_id = b.id
INNER JOIN non_canceled_flights ncf ON b.flight_id = ncf.flight_id 
WHERE bd.last_updated = (SELECT MAX(last_updated) FROM booking_details bd2 WHERE bd2.booking_id = bd.booking_id)
GROUP BY
	b.flight_id